services:
  database:
    image: postgres:16
    container_name: eval-express
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eval_db
    ports:
      - "5445:5432"

  adminer:
    image: adminer
    container_name: eval-adminer
    restart: always
    ports:
      - "8085:8080"
    depends_on:
      - database

volumes:
  postgres_data: